// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oqhvemhomwksenicoktf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xaHZlbWhvbXdrc2VuaWNva3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxNjcwNTksImV4cCI6MjA3ODc0MzA1OX0.SsIwES8kEI84V2XGe9VNAhFtrgvEjqjn467CG34WbWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);